### ISSUE TITLE
Python 3 Compatibility

### ISSUE THREAD

**Issue by rpcope1** [pushrodtechnology/PythonConfluenceAPI#8]
I have no idea if this works well (if at all) with Python 3, as I have only verified it against Python 2.6, 2.7. I (or someone else) should build and run this on a Python 3 instance,  or make the changes necessary to ensure Python 3 future compatibility.

**Comment by ytjohn** [comment]
I've started on this path, going to put a few notes here.
1. setup.py needs a change to the **author** variable, as python3 won't be able to string format. Make it a single string instead of 2 cojoined strings.

`__author__ = 'Robert Cope, Pushrod Technology'`
1. After that change, setup.py does build and install an egg. But importing it fails with not finding the api.

At this point, I'm a bit stumped. I'll look around though. I'm hoping to use this library with errbot.io which is python3 only.

```
>>> from PythonConfluenceAPI import ConfluenceAPI
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/hogenj/projects/PythonConfluenceAPI/PythonConfluenceAPI/__init__.py", line 3, in <module>
    from api import ConfluenceAPI, all_of
ImportError: No module named 'api'
```

**Comment by rpcope1** [comment]
I'll see if I can't figure it out. I've never checked Python 3
compatibility with this library, but I'd agree that's a rather important
thing to have, and I'd like to help you make use of it.

**Comment by ytjohn** [comment]
PR generated.  All minor changes. I added some future imports that weren't absolutely necessary, but will help us keep the code python3 compatible.
